// Login mit Basic Authentication als admin mit korrekten Credentials admin:123
###
# @name loginAdminCorrect
GET http://localhost/api/authenticate
Authorization: Basic YWRtaW46MTIz

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

// Login mit Basic Authentication als admin mit falschen Credentials
// Hinweis: Der REST-Client überführt das Passwort automatisch nach Base64
###
# @name loginAdminIncorrect
GET http://localhost/api/authenticate
Authorization: Basic admin:12345

@incorrectToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDYwY2QwMjE4NWI3Y2M2ZGE1MDU3MDAiLCJ1c2VySUQiOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJhJDEwJGhmbmV4TmZjWG1ZajJ4dVVnUExEZC5LMWJPZjZzeURmdE05dWFYdjBvcW9ObEZHZFZDTVpDIiwiZmlyc3ROYW1lIjoiVWRvIiwibGFzdE5hbWUiOiJNw7xsbGVyIiwiaXNBZG1pbmlzdHJhdG9yIjp0cnVlLCJfX3YiOjAsImlhdCI6MTY4NDA5NTUzNCwiZXhwIjoxNjg0MDk1NTk0fQ.cncx9k4U2Oh-n6qlITuUOBRLKVv6izzzsPrVM-bYPPE

### Auflisten aller Nutzer, ohne dass ein Token übergeben wird --> Anfrage scheitert mit 401 
http://localhost/api/users

### Auflisten aller Nutzer mit Token von admin
http://localhost/api/users
Authorization: {{adminToken}}

### Lege neuen user manfred an
POST http://localhost/api/users
Authorization: {{adminToken}}
Content-Type: application/json

{
    "userID": "manfred",
    "firstName": "Manfred",
    "lastName": "Mustermann",
    "password": "asdf"
}

###

DELETE http://localhost/api/users/manfred
Authorization: {{adminToken}}

### Abrufen des angelegten Users mit dem Admin-Token
GET http://localhost/api/users/manfred
Authorization: {{adminToken}}

// Ändere beim zweiten User den User-Name. Zur Selektion des Users verwende die userID.
###
PUT http://localhost/api/users/manfred
Content-Type: application/json
Authorization: {{adminToken}}

{
    "firstName": "Sandra",
    "lastName": "Müller"
}

// Login mit Basic Authentication als manfred mit korrekten Credentials
###
# @name loginManfredCorrect
GET http://localhost/api/authenticate
Authorization: Basic manfred:asdf

@manfredToken = {{loginManfredCorrect.response.headers.Authorization}}

### Auflisten aller Nutzer mit Token von manfred, das sollte nicht möglich sein
GET http://localhost/api/users
Authorization: {{manfredToken}}

### ?
GET http://localhost/api/users/admin
Authorization: {{manfredToken}}

###

PUT http://localhost/api/users/manfred
Content-Type: application/json
Authorization: {{manfredToken}}

{
    "firstName": "Sandra",
    "lastName": "Test"
}

### Auflisten aller Studiengänge
GET http://localhost/api/degreeCourses
Authorization: {{adminToken}}

// Lege einen Studiengang an
###
# @name createDegreeCourseRequest
POST http://127.0.0.1/api/degreeCourses
Authorization: {{adminToken}}
Content-Type: application/json

{
    "universityName": "Beuth Hochschule für Technik Berlin",
    "universityShortName": "Beuth HS",
    "departmentName": "Informatik und Medien",
    "departmentShortName": "FB VI",
    "name": "Orchideenzucht Bachelor",
    "shortName": "OZ-BA"
}

###
@degreeCourseID = {{createDegreeCourseRequest.response.body.id}}

### Auflisten aller Studiengänge, es sollte jetzt einen geben
http://localhost/api/degreeCourses
Authorization: {{adminToken}}

### Abrufen von dem angelegten Studiengang
http://localhost/api/degreeCourses/{{degreeCourseID}}
Authorization: {{adminToken}}


### Ändere den Namen des Studiengangs
PUT http://localhost/api/degreeCourses/{{degreeCourseID}}
Authorization: {{adminToken}}
Content-Type: application/json

{
    "name": "Medieninformatik"
}

### Auflisten der Studiengänge einer bestimmten Hochschule
GET http://localhost/api/degreeCourses?universityShortName=Beuth HS
Authorization: {{adminToken}}

### Lösche den angelegten Studiengang
DELETE http://localhost/api/degreeCourses/{{degreeCourseID}}
Authorization: {{adminToken}}

### Lösche den User manfred
DELETE http://localhost/api/users/manfred
Authorization: {{adminToken}}