// Rufe alle User ab. Zu Beginn sollten keine User in der Datenbank sein. 
###
GET http://localhost/api/publicUsers

// Lege ersten User an, der Administrator ist
###
POST http://localhost/api/publicUsers
Content-Type: application/json

{
    "userID": "admin",
    "firstName": "Udo",
    "lastName": "Müller",
    "password": "123",
    "isAdministrator": true
}

// Rufe den User mit UserID admin ab. 
###
GET http://localhost/api/publicUsers/admin

// Lege zweiten User an. Prüfe UserID sowie den Namen, ob die Angaben korrekt sind.
###
POST http://localhost/api/publicUsers
Content-Type: application/json

{
    "userID": "manfred",
    "firstName": "Susi",
    "lastName": "Sunkist",
    "password": "eliasistcool1"
}

// Ändere beim zweiten User den User-Name. Zur Selektion des Users verwende die userID.
###
PUT http://localhost/api/publicUsers/manfred
Content-Type: application/json

{
    "password": "1234",
    "isAdministrator": true
}

// Rufe alle User ab. Es sollten 2 User zurückgegeben werden.
###
GET http://localhost/api/publicUsers

// Lösche den User mit der User-ID manfred
###
DELETE  http://localhost/api/publicUsers/manfred

// check login
###
POST http://localhost/api/publicUsers/login
Content-Type: application/json

{
    "userID": "admin",
    "password": "123"
}

// remove non existing
###
DELETE  http://localhost/api/publicUsers/blablo

// change non existing
###
PUT  http://localhost/api/publicUsers/blablo

// User without ID.
###
POST http://localhost/api/publicUsers
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test2",
    "password": "password"
}